<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:macro name="link_macro" params="suffix parent joint x_offset y_offset z_offset width length height mass com_x com_y com_z ixx ixy ixz iyy iyz izz color">
        <xacro:if value="${joint=='revolute'}">
            <joint name="${suffix}_joint" type="revolute">
                <parent link="${parent}_link"/>
                <child link="${suffix}_link"/>
                <origin xyz="${x_offset} ${y_offset} ${z_offset}" rpy="0 0 0"/>
                <limit lower="-${PI/2}" upper="${PI/2}" effort="1" velocity="100"/>
                <axis xyz="0 1 0"/>
                <dynamics damping="0.0"/>
            </joint>
            <transmission name="${suffix}_transmission">
                <type>transmission_interface/SimpleTransmission</type>
                <joint name="${suffix}_joint">
                    <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
                </joint>
                    <actuator name="${suffix}_motor">
                        <hardwareInterface>EffortJointInterface</hardwareInterface>
                        <mechanismReduction>1</mechanismReduction>
                    </actuator>
                </transmission>
                <gazebo reference="${suffix}_joint">
                    <provideFeedback>true</provideFeedback>
                    <turnGravityOff>false</turnGravityOff>
                </gazebo>
        </xacro:if>

        <xacro:if value="${joint=='continuous'}">
            <joint name="${suffix}_joint" type="continuous">
                <parent link="${parent}_link"/>
                <child link="${suffix}_link"/>
                <origin xyz="${x_offset} ${y_offset} ${z_offset}" rpy="${PI} 0 0"/>
                <limit effort="0" velocity="100"/>
                <axis xyz="0 1 0"/>
                <dynamics damping="0.0"/>
            </joint>
            <gazebo reference="${suffix}_joint">
                <provideFeedback>true</provideFeedback>
                <turnGravityOff>false</turnGravityOff>
            </gazebo>
        </xacro:if>


        <link name="${suffix}_link">
            <visual>
                <geometry>
                    <box size="${width} ${length} ${height}"/>
                </geometry>
                <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
                <material name="${color}"/>
            </visual>

            <inertial>
                <origin xyz="${com_x} ${com_y} ${com_z}" rpy="0 0 0"/>
                <mass value="${mass}"/>
                <inertia
                    ixx="${ixx}" ixy="${ixy}" ixz="${ixz}"
                    iyy="${iyy}" iyz="${iyz}"
                    izz="${izz}"/>
            </inertial>

            <collision>
                <geometry>
                    <box size="${width} ${length} ${height}"/>
                </geometry>
                <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
            </collision>
        </link>
        <gazebo reference="${suffix}_link">
            <material>Gazebo/${color}</material>
            <selfCollide>true</selfCollide>
        </gazebo>



    </xacro:macro>
</robot>
