<?xml version="1.0" ?>

<robot name="xacro_test" xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:property name="width" value="0.1"/>
    <xacro:property name="length" value="0.3"/>
    <xacro:property name="height" value="1.0"/>

    <xacro:property name="PI" value="3.1415"/>

    <link name="base_link"/>

    <joint name="base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="1st_link"/>
    </joint>

    <link name="1st_link">
        <visual>
            <geometry>
                <box size="${width} ${length} ${height}" rpy="0 0 0"/>
            </geometry>
            <material name="red">
                <color rgba="1.0 0.0 0.0 1.0"/>
            </material>
            <origin xyz="0 0 ${height/2.0}" rpy="0 0 0"/>
        </visual>
    </link>

    <joint name="waist_link" type="revolute">
        <parent link="1st_link"/>
        <child link="2nd_link"/>
        <origin xyz="0 0 ${height}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit lower="-${PI}" upper="${PI}" effort="0" velocity="0"/>
        <dynamics damping="0.1" friction="0"/>
    </joint>

    <link name="2nd_link">
        <visual>
            <geometry>
                <box size="${width} ${length} ${height}" rpy="0 0 0"/>
            </geometry>
            <material name="blue">
                <color rgba="0 0 1 1"/>
            </material>
            <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
        </visual>
    </link>

</robot>
