gymnast_robot:
    
    # Position controller
    2nd_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: 2nd_joint
        pid: {p: 100.0, i: 0.01, d: 10.0}

    3rd_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: 3rd_joint
        pid: {p: 100.0, i: 0.01, d: 10.0}

