<?xml version="1.0"?>
<robot name="IB_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- importing macro,constants,.gazebo files -->
    <!-- robot mechanical parameters -->
    <xacro:include filename="$(find simulate_robot)/urdf/system_constants.xacro"/>
    <xacro:include filename="$(find simulate_robot)/urdf/link_macro.xacro"/>
    <!-- Rviz material colors -->
    <xacro:include filename="$(find simulate_robot)/urdf/material_parameter.xacro"/>
    <!-- Gazebo custom tags,materials -->
    <xacro:include filename="$(find simulate_robot)/urdf/acrobat_robot_IB.gazebo"/>
    
    <!-- fixed base_link -->
    <link name="world"/>

    <joint name="world_fixed" type="fixed">
        <parent link="world"/>
        <child link="base"/>
    </joint>

    <!-- base_link -->
    <link name="base">
        <visual><!-- visual config -->
            <origin xyz="0 0 ${(height1+height2+0.10)/2}" rpy="0 0 0"/>
            <material name="white"/>
            <geometry>
                <box size="0.05 0.05 ${height1+height2+0.10}"/>
            </geometry>
        </visual>
        <collision><!-- Gazebo collision config -->
            <origin xyz="0 0 ${(height1+height2+10)/2}" rpy="0 0 0"/>
            <geometry>
                <box size="0.05 0.05 ${height1+height2+0.10}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 ${(height1+height2+10)/2}" rpy="0 0 0"/>
            <mass value="100"/>
            <inertia 
                ixx="10" ixy="0" ixz="0"
                iyy="10" iyz="0"
                izz="10"/>
        </inertial>
    </link>

    <!-- 1st_link -->
    <xacro:link_macro 
        suffix="1st_link" parent="base" type="continuous" color="orange" 
        width="${width1}" length="${length1}" height="${height1}" x_offset="0" y_offset="${width1}" z_offset="${height1+height2+0.10}" 
        mass="${mass1}" comx="${comx1}" comy="${comy1}" comz="${comz1}"
        ixx="0.01" ixy="0" ixz="0" 
        iyy="0.01" iyz="0" 
        izz="0.0058"/>
    <!-- 2nd_link -->
    <xacro:link_macro 
        suffix="2nd_link" parent="1st_link" type="revolute" color="green" 
        width="${width2}" length="${length2}" height="${height2}" x_offset="0" y_offset="${width2}" z_offset="${height1}" 
        mass="${mass1}" comx="${comx2}" comy="${comy2}" comz="${comz2}"
        ixx="0.01" ixy="0" ixz="0" 
        iyy="0.01" iyz="0" 
        izz="0.070"/>
</robot>